kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gceme-frontend-dev
spec:
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: gceme
        role: frontend
        env: dev
    spec:
      containers:
      - name: frontend
        image: gcr.io/vic-goog/sample-app-frontend
        command:
        - /go/src/frontend/frontend
        args:
        - -backend-service=http://gceme-backend:8080
        env:
        - name: VERSION
          value: v1.0.1
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
        ports:
        - name: frontend
          containerPort: 80
