apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy: sha256
  artifacts:
  - imageName: gcr.io/vic-goog/sample-app
    dockerfilePath: Dockerfile
  googleCloudBuild:
    projectId: vic-goog
deploy:
  kubectl:
    manifests:
    - paths:
      - k8s/dev/*
      - k8s/services/*
      parameters:
        IMAGE_NAME: gcr.io/vic-goog/sample-app
