apiVersion: skaffold/v1alpha3
kind: Config
build:
  artifacts:
  - imageName: gcr.io/vic-bin-authz-0/gceme
  googleCloudBuild:
    projectId: vic-bin-authz-0
deploy:
  kubectl:
    manifests:
    - k8s/dev/backend-dev.yaml
    - k8s/dev/default.yml
    - k8s/dev/frontend-dev.yaml
