apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - imageName: gcr.io/vic-goog/sample-app-backend
    workspace: cmd/backend
  - imageName: gcr.io/vic-goog/sample-app-frontend
    workspace: cmd/frontend
deploy:
  kubectl:
    manifests:
      - k8s/dev/backend-dev.yaml
      - k8s/services/backend.yaml
      - k8s/dev/frontend-dev.yaml
      - k8s/services/frontend.yaml