kind: Deployment
apiVersion: apps/v1
metadata:
  name: gceme-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gceme
      role: backend
      env: dev
  template:
    metadata:
      name: backend
      labels:
        env: dev
    spec:
      containers:
      - name: backend
        image: gcr.io/vic-cd-demo/sample-app-backend
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: VERSION
          value: dev
        imagePullPolicy: Always
