kind: Deployment
apiVersion: apps/v1
metadata:
  name: gceme-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gceme
      role: frontend
      env: prod
  template:
    metadata:
      name: frontend
      labels:
        app: gceme
        role: frontend
        env: prod
    spec:
      containers:
      - name: frontend
        image: gcr.io/vic-cd-demo/sample-app-backend
        command:
        - /go/src/frontend/frontend
        args:
        - -backend-service=http://gceme-backend:8080
        env:
        - name: VERSION
          value: v1.0.1
        resources:
          limits:
            memory: "1000Mi"
            cpu: "500m"
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
        ports:
        - name: frontend
          containerPort: 80
